theme: jekyll-theme-cayman
title: Isabelle Quick Access Links
description: Quicklinks to all important sites related to the Isabelle theorem prover

collections:
  shortlinks:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: _shortlinks
      type: shortlinks
    values:
      layout: shortlink
